[package]
name = "gtk-input"
version = "0.1.0"
authors = ["Xnuk Shuman <admin@xnu.kr>"]
edition = "2018"

[dependencies]
gtk = "^0.9.2"
gdk = "^0.13.0"
gtk-sys = "^0.10.0"

[[bin]]
name = "gtk-input"
path = "main.rs"

[profile.release]
opt-level = 'z'
lto = true
panic = 'abort'
